[features]
seeds = false
skip-lint = false
[programs.localnet]
fuzz_example3 = "FzwXe6bxBZXcqmkdv37YvFARRvqh2JvPW8RrLiTrZTtP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fuzz_example3_steal.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fuzz_example3_block.ts"
